# FROM
# 베이스 이미지 지정 ex) FROM httpd:alpine

# LABEL
# 버전 정보, 작성자 등의 이미지 설명을 위한 명령

# CMD
# docker 컨테이너가 시작할 때, 실행하는 쉘 명령을 지정

# RUN
# 쉘 명령을 실행하는 명령

# ENTRYPOINT
# docker 컨테이너가 시작할 때, 실행하는 쉘 명령을 지정하는 명령

# EXPOSE
# 컨테이너 외부에 오픈할 포트 설정

# ENV
# 컨테이너에서 내부에서 사용할 환경 변수 지정

# WORKDIR
# 컨테이너에서의 작업 디렉토리

# COPY
# 파일 또는 디렉토리를 컨테이너에 복사
# ex) COPY ./2021_DEV /usr/local/apache2/htdocs
# => 2021_DEV 폴더를 컨테이너 내부에서 /usr/local/apache2/htdocs 위치로 복사 (apache2 를 예시로한거라서 복사가 될 경로는 경우마다 다름)

## 예시 작성 법
FROM httpd:alpine

LABEL maintainer="inajung"
LABEL version="1.0.0"

COPY ./2021_DEV /user/local/apache2/htdocs

CMD ["/bin/sh", "-c", "httpd-foreground"]